Update patch set 1
Patch Set 1:

(1 comment)

Thanks for cleanup!

Patch-set: 1

diff --git a/6ab8c09a21c81234647fbde2f0d3f1c497435c59 b/6ab8c09a21c81234647fbde2f0d3f1c497435c59
--- a/6ab8c09a21c81234647fbde2f0d3f1c497435c59
+++ b/6ab8c09a21c81234647fbde2f0d3f1c497435c59
@@ -2,6 +2,20 @@ Revision: 6ab8c09a21c81234647fbde2f0d3f1c497435c59
 Patch-set: 1
 File: test/etc/run-test-jar
 
+201
+Mon Oct 26 17:38:33 2015 +0000
+Author: Igor Murashkin <1021471@85c56323-6fa9-3386-8a01-6480fb634889>
+UUID: 56e941ce_f006e8ee
+Bytes: 108
+maybe add a 
+
+   if [ "$#" -lt 2 ]; then
+     echo "missing --experimental option" 1>&2
+     exit 1
+   fi
+
+?
+
 202:6-203:13
 Mon Oct 26 17:31:54 2015 +0000
 Author: Igor Murashkin <1021471@85c56323-6fa9-3386-8a01-6480fb634889>
